#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to
# another page with 301 Moved Permanently

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo 'Hello World!' > /etc/nginx/html/index.html

CONFIGRATION=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://github.com/Y-Baker;
    }
}"
bash -c "echo -e '$CONFIGRATION' > /etc/nginx/sites-available/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
