#!/usr/bin/env bash
# custom 404 page that contains the string 
# Ceci n'est pas une page

apt-get update -y
apt-get install nginx -y
ufw allow 'Nginx HTTP'

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo 'Hello World!' > /etc/nginx/html/index.html

touch /etc/nginx/html/error_404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/error_404.html

CONFIGRATION=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://github.com/Y-Baker;
	}

	error_page 404 /error_404.html;
	location /404 {
		root /etc/nginx/html;
		internal;
	}
}"
bash -c "echo -e '$CONFIGRATION' > /etc/nginx/sites-available/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
